#!/bin/bash

# Script to generate SNAPSHOT version for local development
# Format: MAJOR.MINOR.PATCH-BRANCH.COMMIT

# Get the base version from pubspec.yaml
BASE_VERSION=$(grep "^version:" pubspec.yaml | sed 's/version: \([0-9.]*\).*/\1/')

# Get current git branch name (sanitized for version string)
BRANCH=$(git rev-parse --abbrev-ref HEAD | sed 's/[^a-zA-Z0-9-]/-/g')

# Get short commit hash
COMMIT=$(git rev-parse --short HEAD)

# Get build number as total number of commits
BUILD_NUMBER=$(git rev-list --count HEAD)

# Construct the SNAPSHOT version (without build number)
SNAPSHOT_VERSION="${BASE_VERSION}-${BRANCH}.${COMMIT}"

# Update local.properties with SNAPSHOT version info
LOCAL_PROPS="android/local.properties"

# Remove existing snapshot properties and empty lines if present
sed -i '' '/^snapshot\.versionCode=/d' "$LOCAL_PROPS" 2>/dev/null || true
sed -i '' '/^snapshot\.versionName=/d' "$LOCAL_PROPS" 2>/dev/null || true

echo "snapshot.versionCode=${BUILD_NUMBER}" >> "$LOCAL_PROPS"
echo "snapshot.versionName=${SNAPSHOT_VERSION}" >> "$LOCAL_PROPS"

# Update iOS Snapshot.xcconfig with the version info
# Get the script's parent directory (project root)
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_ROOT="$( cd "$SCRIPT_DIR/.." && pwd )"
IOS_SNAPSHOT_CONFIG="$PROJECT_ROOT/ios/Flutter/Snapshot.xcconfig"

# Create iOS Flutter directory if it doesn't exist
mkdir -p "$PROJECT_ROOT/ios/Flutter"

# Generate iOS Snapshot.xcconfig
cat > "$IOS_SNAPSHOT_CONFIG" << EOF
// SNAPSHOT version configuration
// This file is auto-generated by generate_snapshot_version.sh
// DO NOT EDIT MANUALLY

FLUTTER_BUILD_NAME = ${SNAPSHOT_VERSION}
FLUTTER_BUILD_NUMBER = ${BUILD_NUMBER}
EOF

# Export as environment variables
export FLUTTER_BUILD_NAME="${SNAPSHOT_VERSION}"
export FLUTTER_BUILD_NUMBER="${BUILD_NUMBER}"
export SNAPSHOT_VERSION_NAME="${SNAPSHOT_VERSION}"
export SNAPSHOT_BUILD_NUMBER="${BUILD_NUMBER}"

echo "Generated SNAPSHOT version: ${SNAPSHOT_VERSION}"
echo "Version code/Build number: ${BUILD_NUMBER}"
echo "Updated ${LOCAL_PROPS} (Android)"
echo "Updated ${IOS_SNAPSHOT_CONFIG} (iOS)"
echo ""
echo "Environment variables exported:"
echo "  SNAPSHOT_VERSION_NAME=${SNAPSHOT_VERSION}"
echo "  SNAPSHOT_BUILD_NUMBER=${BUILD_NUMBER}"